config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper_openid_connect
  use_doorkeeper
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"
  mount MissionControl::Jobs::Engine, at: "/organization/jobs"
  mount DemoMode::Engine => "/demo"
  mount LetterOpenerWeb::Engine, at: "/organization/letters" if Rails.application.config.action_mailer.delivery_method == :letter_opener

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal healconfig.action_mailer.delivery_method = :letter_openerth status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "my/memberships#new"

  namespace :organization do
    root "members#index", as: :members

    resources :members, param: :username, except: [:index, :edit, :delete] do
      collection do
        resources :exports, only: [:show], param: :type, module: :member
      end
    end

    resources :broadcasts, only: [:index, :destroy, :create]

    resource :config, except: [:edit, :destroy]

    resource :journey, only: [:new, :create] do
      collection do
        resources :strategies, only: [:index], shallow: true, as: "journey_strategies", module: :journey do
          collection do
            scope module: :strategies do
              namespace :password do
                resources :authentications, only: [:new, :create]
              end
              namespace :passkey do
                resources :authentications, only: [:new, :create]
              end
            end
          end
        end
        get "/delete", to: "journeys#delete"
      end
    end

    get "/cemetery", to: "cemeteries#index"
    get "/petitions", to: "petitions#index"

    resources :api_keys, only: [:index, :create, :destroy]

    # TODO: shallow nest inside of Config
    resources :passkeys, only: [:index, :new, :create, :destroy]
  end

  namespace :api do
    resources :members, param: :username, except: [:new, :edit, :delete] do
      member do
        resource :actor, only: :show, module: :member, as: :member_actor, controller: :actors
      end
    end
    resources :broadcasts, except: [:new, :edit, :delete, :update]
  end
  
  namespace :my do
    root to: redirect("/my/membership")

    resource :journey, only: [:new, :create] do
      collection do
        resources :strategies, only: [:index], shallow: true, as: "journey_strategies", module: :journey do
          collection do
            scope module: :strategies do
              namespace :keycode do
                resources :authentications, only: [:new, :create]
              end
              namespace :passkey do
                resources :authentications, only: [:new, :create]
              end
            end
          end
        end
        get "/delete", to: "journeys#delete"
      end
    end

    resource :membership, only: [:new, :create, :show, :update, :destroy] do
      resource :renewals, only: [:create], module: :membership
    end

    namespace :imprint do
      resource :rotations, only: [:create]
    end

    resources :passkeys, only: [:index, :new, :create, :destroy]
  end

  resolve("Membership") { [:membership] }
  resolve("Journey") { [:journey] }
  resolve("Config") { [:config] }
end

app/models/config.rb
class Config < ApplicationRecord
  include Organization::Keyable

  before_create :check_for_existing
  before_destroy :check_for_existing
  self.table_name = "configurations"
  broadcasts_refreshes

  serialize :extensions, type: Array, coder: SymbolJSON

  has_secure_password

  store :smtp, accessors: [:server, :port, :username, :password, :box, :domain], prefix: true

  before_save do
    self.email = email.downcase
  end

  validate do |c|
    if !Array.wrap(c.extensions).try(:all?, ->(e) { e.is_a? Symbol })
      errors.add :extensions, :invalid_type, message: "does not decode to an Array of Symbols"
    end
  end

  after_save_commit do
    if oidc_key.blank?
      update!(oidc_key: OpenSSL::PKey::RSA.new(2048))
    end
    begin
      Doorkeeper::OpenidConnect.configuration.instance_variable_set(:@signing_key, oidc_key)
    rescue Doorkeeper::OpenidConnect::Errors::MissingConfiguration
      Rails.logger.info "config: openid connect not initialized yet, not setting @signing_key"
    end
  end

  after_initialize do
    update!(oidc_key: Rails.application.credentials&.oidc&.[](:key).presence ||
    oidc_key.presence ||
    OpenSSL::PKey::RSA.new(2048))
  end

  after_save_commit do
    hash = {}
    (extensions || []).each do |e|
      hash[e] = e.to_s
    end
    Extension.enum :name, hash, instance_methods: false, validate: {allow_nil: true} unless try(:extensions).blank?
  end

  def self.extensions_enum
    hash = {}
    (try(:extensions) || []).each do |e|
      hash[e] = e.to_s
    end
    hash
  end

  class << self
    Config.connection
    Config.column_names.each do |k|
      delegate k, to: :first, allow_nil: true
    end

    delegate :cache_key_with_version, to: :first, allow_nil: true
  end

  private

  def check_for_existing
    raise ActiveRecord::RecordInvalid if Config.count >= 1
  end
end

app/models/organization/keyable.rb
module Organization::Keyable
  extend ActiveSupport::Concern

  included do
    has_one :keyring, as: :keyable, dependent: :destroy, class_name: "Organization::Keyring"
  end

  class_methods do
    delegate :keyring, to: :first, allow_nil: true

    delegate :create_keyring, to: :first
  end
end

app/models/organization/keyring.rb
class Organization::Keyring < Keyring
  self.relying_party = WebAuthn::RelyingParty.new(
    origin: Config.external_url,
    name: "#{Config.organization} Administration"
  )
  attribute :type, :string, default: -> { "Organization::Keyring" }
end

app/controllers/organization/api_keys_controller.rb
class Organization::ApiKeysController < Organization::BaseController
  def index
  end

  def create
    p = SecureRandom.base64(54)
    a = Api::Key.create! api_key_params.merge({password: p})
    redirect_back fallback_location: organization_api_keys_path, flash: {"#{a.id}_api_key": p}
  end

  def destroy
    Api::Key.find_by(id: params[:id]).destroy!
    redirect_back fallback_location: organization_api_keys_path
  end

  private

  def api_key_params
    params.require(:api_key).permit(:id, :name)
  end
end

app/controllers/organization/base_controller.rb
class Organization::BaseController < ApplicationController
  before_action :ensure_authenticated
  add_breadcrumb "Organization", :organization_members_path

  def ensure_authenticated
    if !request.env["warden"].authenticated?
      Journey.basecamp = request.env["PATH_INFO"]
      redirect_to new_organization_journey_path
    end
  end

  private

  # For demo mode
  def current_user
    request.env["warden"].user
  end

  def sign_out
    request.env["warden"].logout
  end

  def sign_in(config)
    request.env["warden"].set_user(config)
  end
end

app/controllers/organization/broadcasts_controller.rb
class Organization::BroadcastsController < Organization::BaseController
  def new
  end

  def create
    Broadcast.create! broadcast_params
    redirect_back fallback_location: organization_broadcasts_path
  end

  private

  def broadcast_params
    params.require(:broadcast).permit(:subject, :content)
  end
end

app/controllers/organization/cemeteries_controller.rb
class Organization::CemeteriesController < Organization::BaseController
  add_breadcrumb "Cemetery", :organization_cemetery_path
  def index
    @members = Member.cemetery
  end
end

app/controllers/organization/configs_controller.rb
class Organization::ConfigsController < Organization::BaseController
  skip_before_action :ensure_configured, :ensure_authenticated, only: [:new, :create]

  def new
    if Config.first
      redirect_to organization_members_path, flash: {error: "This instance is already configured"}
    end
  end

  def create
    if Config.first
      redirect_to organization_members_path, flash: {error: "This instance is already configured"}
      return
    end
    c = Config.new(config_params)
    c.save!
    redirect_to organization_members_path
  end

  def show
  end

  def update
    c = Config.first
    c.assign_attributes(config_params)
    if c.invalid?
      errors = "<ul>"
      c.errors.full_messages.each do |e|
        errors += "<li>#{e}</li>"
      end
      errors += "</ul>"
      flash.now[:error] = errors
      render :show, status: :unprocessable_entity
      return
    end
    c.save!
    redirect_back fallback_location: organization_config_path
  end

  private

  def config_params
    params.require(:config).permit(:organization, :external_url, :membership_length, :clearing, :email, :password, extensions: [], smtp: [:server, :port, :username, :password, :box, :domain])
  end
end

app/controllers/organization/journey/base_controller.rb
class Organization::Journey::BaseController < Organization::BaseController
  layout "organization/journeys"

  skip_before_action :ensure_authenticated

  add_breadcrumb "Journey", :new_organization_journey_path
end

app/controllers/organization/journey/strategies/base_controller.rb
class Organization::Journey::Strategies::BaseController < Organization::Journey::BaseController
  add_breadcrumb "Strategies", :organization_journey_strategies_path
end

app/controllers/organization/journey/strategies/passkey/authentications_controller.rb
class Organization::Journey::Strategies::Passkey::AuthenticationsController < Organization::Journey::Strategies::BaseController
  def new
    @options = Journey.explorer.keyring.relying_party.options_for_authentication

    Passkey::Ceremony.reset
    Passkey::Ceremony.challenge = @options.challenge

    add_breadcrumb "Passkey", :new_organization_passkey_authentication_path
  end

  def create
    request.env["warden"].authenticate(:organization_passkey)
    if !request.env["warden"].authenticated?
      flash[:error] = "Unable to log in"
      redirect_back fallback_location: new_organization_passkey_authentication_path, status: :see_other
      return
    end
    redirect_to (Journey.basecamp || organization_members_path), status: :see_other
  end
end

app/controllers/organization/journey/strategies/password/authentications_controller.rb
class Organization::Journey::Strategies::Password::AuthenticationsController < Organization::Journey::Strategies::BaseController
  def new
    add_breadcrumb "Password", new_organization_password_authentication_path
  end

  def create
    request.env["warden"].authenticate(:organization_password)
    if !request.env["warden"].authenticated?
      flash[:error] = "Unable to log in"
      redirect_back fallback_location: new_organization_password_authentication_path
      return
    end
    redirect_to Journey.basecamp || organization_members_path, status: :see_other
  end
end

app/controllers/organization/journey/strategies_controller.rb
class Organization::Journey::StrategiesController < Organization::Journey::Strategies::BaseController
  def index
    @strategies = [{
      name: "Password",
      path: new_organization_password_authentication_path,
      icon: "password.svg"
    }]

    if Journey.explorer&.keyring
      @strategies.push({
        name: "Passkey",
        path: new_organization_passkey_authentication_path,
        icon: "passkey.svg"
      })
    end
  end
end

app/controllers/organization/journeys_controller.rb
class Organization::JourneysController < Organization::Journey::BaseController
  def new
    basecamp = Journey.basecamp
    Journey.reset
    Journey.basecamp = basecamp
  end

  def create
    Journey.explorer = Config.find_by(email: config_params[:email].downcase)
    redirect_to organization_journey_strategies_path, status: :see_other
  end

  def delete
    request.env["warden"].logout
    redirect_to new_organization_journey_path
  end

  private

  def config_params
    params.require(:config).permit(:email)
  end
end

app/controllers/organization/member/exports_controller.rb
class Organization::Member::ExportsController < Organization::BaseController
  def show
    members = Member.order(created_at: :desc)
    @export = members.extend(Exportable).export(params[:type])
    render csv: @export.to_data,
      filename: @export.filename
  end
end

app/controllers/organization/members_controller.rb
class Organization::MembersController < Organization::BaseController
  include ActiveSupport::Inflector

  def index
    @members = Member.order(created_at: :desc)
    respond_to do |format|
      format.html
    end
  end

  def show
    @member = Member.include_deceased.include_petitioners.find_by(username: params[:username])
    add_breadcrumb @member.username, organization_member_path(params[:username])
  end

  def update
    member = Member.include_deceased.include_petitioners.find_by(username: params[:username])
    if member.deceased?
      member.resurrect
    end
    if member.petitioning?
      member.approve!
    end
    member.update!(member_params.merge!({extensions_attributes: mapped_extensions}))
    redirect_to organization_members_path
  end

  def destroy
    member = Member.include_deceased.include_petitioners.find_by(username: params[:username])
    if member.petitioning?
      member.reject!
      member.cremate!
    elsif member.deceased?
      member.cremate!
    else
      member.decease
    end
    redirect_to organization_members_path, status: 303
  end

  private

  def member_params
    params.require(:member).permit(:name, :username, :email, :expires_at, :banned, address_attributes: [:line1, :line2, :city, :province, :code, :country], extensions_attributes: {})
  end

  def mapped_extensions
    attrs = member_params[:extensions_attributes] || {}
    attrs.keys.map { |e| {name: e, content: attrs[e]} }
  end
end

app/controllers/organization/passkeys_controller.rb
class Organization::PasskeysController < Organization::BaseController
  def index
  end

  def new
    if !Config.keyring
      Config.create_keyring
    end

    @options = Config.keyring.relying_party.options_for_registration(
      user: {id: Config.keyring.id, name: Config.email, display_name: Config.email},
      exclude: Config.keyring.passkeys.map { |p| p.id },
      authenticator_selection: {
        residentKey: "required",
        requireResidentKey: true,
        userVerification: "preferred"
      }
    )

    Passkey::Ceremony.reset
    Passkey::Ceremony.challenge = @options.challenge
  end

  def create
    webauthn_credential = Config.keyring.relying_party.verify_registration(
      JSON.parse(passkey_params[:credential]),
      Passkey::Ceremony.challenge
    )

    Config.keyring.passkeys.create!(
      id: webauthn_credential.id,
      name: passkey_params[:name],
      public_key: webauthn_credential.public_key,
      sign_count: webauthn_credential.sign_count
    )

    redirect_to organization_passkeys_path, status: :see_other
  end

  def destroy
    Config.keyring.passkeys.find(params[:id]).destroy!
    redirect_to organization_passkeys_path, status: :see_other
  end

  private

  def passkey_params
    params.require(:passkey).permit(:challenge, :credential, :name, :id)
  end
end

app/controllers/organization/petitions_controller.rb
class Organization::PetitionsController < Organization::BaseController
  add_breadcrumb "Clearance Petitions", :organization_petitions_path
  def index
    @members = Member.petitioners
  end
end

app/views/organization/configs/new.html.erb
<header>
  <h1>Welcome to United!</h1>
</header>
<main id="main">
  <%= form_with scope: :config, url: organization_config_path, method: :post do |form| %>
    <div>
      <%= form.label :organization, "Organization name" %>
      <%= form.text_field :organization, placeholder: "United Workers" %>
    </div>

    <div>
      <%= form.label :external_url, "External URL" %>
      <%= form.url_field :external_url, placeholder: "https://united.obl.ong" %>
    </div>

    <div>
      <%= form.label :membership_length, "Membership length (in days, -1 disables expiry)" %>
      <%= form.number_field :membership_length, placeholder: "365" %>
    </div>

    <div>
      <%= form.label :clearing, "Review memberships after sign-up" %>
      <%= form.check_box :clearing %>
    </div>

    <div>
      <%= form.label :email, "Your email" %>
      <%= form.text_field :email, placeholder: "fionahu@obl.ong" %>
    </div>

    <div>
      <%= form.label :password, "Your password" %>
      <%= form.password_field :password, placeholder: "password123" %>
    </div>

    <br>
    <h2 style="margin: 0">Email server (SMTP) information</h2>

    <%= form.fields_for :smtp do |smtp_form| %>

    <div style="display: flex; flex-direction: row; justify-content: space-between;">
      <div style="flex-grow: 1">
        <%= smtp_form.label :server, "Server" %>
        <%= smtp_form.text_field :server, placeholder: "smtp.gmail.com", style: "display: flex;" %>
      </div>

      <div>
        <%= smtp_form.label :port, "Port" %>
        <%= smtp_form.number_field :port, placeholder: "587", style: "display: flex;" %>
      </div>
    </div>

    <div>
      <%= smtp_form.label :username, "Username" %>
      <%= smtp_form.text_field :username, placeholder: "fionahu" %>
    </div>

    <div>
      <%= smtp_form.label :password, "Password" %>
      <%= smtp_form.password_field :password, placeholder: "password123" %>
    </div>

    <div style="display: flex; flex-direction: row; justify-content: space-between;">
      <div>
        <%= smtp_form.label :box, "Box" %>
        <%= smtp_form.text_field :box, placeholder: "united", style: "display: flex;min-width: 0;" %>
      </div>
      <p style="margin-top: 30px;margin-bottom: 0;">@</p>
      <div style="flex-grow: 1">
        <%= smtp_form.label :domain, "Domain" %>
        <%= smtp_form.text_field :domain, placeholder: "obl.ong", style: "display: flex;min-width: 0;" %>
      </div>
    </div>
    <% end %>

    <%= form.submit "Get started →" %>
  <% end %>
</main>

app/views/organization/configs/show.html.erb
<%= render "nav" %>

<header>
  <h1 style="margin-bottom: 0.5rem;">Configuration</h1>
  <nav aria-label="Actions" class="subheading-buttons">
    <% if Rails.application.config.action_mailer.delivery_method == :letter_opener %>
      <%= link_to try(:letter_opener_web_path) do %>
        <button class="subheading-button">View emails</button>
      <% end %>
      <%= link_to mission_control_jobs_path do %>
        <button class="subheading-button">View jobs</button>
      <% end %>
    <% end %>
  </nav>
</header>
<%= turbo_stream_from Config.first %>
<main id="main">
  <%= form_with model: Config.first, scope: :config, url: organization_config_path, method: :patch do |form| %>
    <div>
      <%= form.label :organization, "Organization name" %>
      <%= form.text_field :organization, placeholder: "United Workers" %>
    </div>
    <div>
      <%= form.label :external_url, "External URL" %>
      <%= form.url_field :external_url, placeholder: "https://united.obl.ong" %>
    </div>
    <div>
      <%= form.label :membership_length, "Membership length (in days, -1 disables expiry)" %>
      <%= form.number_field :membership_length, placeholder: "365" %>
    </div>
    <div>
      <%= form.label :clearing, "Review memberships after sign-up" %>
      <%= form.check_box :clearing %>
    </div>
    <br>
    <h2 style="margin: 0; margin-top: 0.5rem;">Authentication</h2>
    <div>
      <%= form.label :email, "Your email" %>
      <%= form.text_field :email, placeholder: "fionahu@obl.ong" %>
    </div>
    <div>
      <%= form.label :password, "Your password" %>
      <%= form.password_field :password, placeholder: "password123" %>
    </div>
    <br>
    <div>
      <label>Passkeys <a style="text-decoration: underline; color: var(--green-8)" href="https://www.eff.org/deeplinks/2023/10/what-passkey">(what are these?)</a></label>
      <%= turbo_frame_tag (Config.keyring || Config.create_keyring).id, src: organization_passkeys_path, style: "width: 100%;" %>
    </div>
    <br>
    <h2 style="margin: 0">Email server (SMTP) information</h2>

    <%= form.fields_for :smtp do |smtp_form| %>
      <div style="display: flex; flex-direction: row; justify-content: space-between;">
        <div style="flex-grow: 1">
          <%= smtp_form.label :server, "Server" %>
          <%= smtp_form.text_field :server, placeholder: "smtp.gmail.com", value: Config.first.smtp[:server], style: "display: flex;" %>
        </div>

        <div>
          <%= smtp_form.label :port, "Port" %>
          <%= smtp_form.number_field :port, value: Config.first.smtp[:port], placeholder: "587", style: "display: flex;" %>
        </div>
      </div>

      <div>
        <%= smtp_form.label :username, "Username" %>
        <%= smtp_form.text_field :username, value: Config.first.smtp[:username], placeholder: "fionahu" %>
      </div>

      <div>
        <%= smtp_form.label :password, "Password" %>
        <%= smtp_form.password_field :password, value: Config.first.smtp[:password], placeholder: "password123" %>
      </div>

      <div style="display: flex; flex-direction: row; justify-content: space-between;">
        <div>
          <%= smtp_form.label :box, "Box" %>
          <%= smtp_form.text_field :box, value: Config.first.smtp[:box], placeholder: "united", style: "display: flex;min-width: 0;" %>
        </div>
        <p style="margin-top: 30px;margin-bottom: 0;">@</p>
        <div style="flex-grow: 1">
          <%= smtp_form.label :domain, "Domain" %>
          <%= smtp_form.text_field :domain, value: Config.first.smtp[:domain], placeholder: "obl.ong", style: "display: flex;min-width: 0;" %>
        </div>
      </div>
    <% end %>
    <br>
    <h2 style="margin: 0">Member Fields</h2>
    <p style="margin: 0">This section allows you to add custom fields for your members to fill out. <br><br>You can only add 3 new fields at a time; after updating, 3 more fields will appear.</p>

    <%= form.fields :extensions do |f| %>
      <% Config.first[:extensions].each do |e| %>
        <%= f.text_field nil, id: nil, value: ActiveSupport::Inflector.humanize(e), title: "Member Field" %>
      <% end %>
      <%= f.text_field nil, id: nil, title: "Member Field" %>
      <%= f.text_field nil, id: nil, title: "Member Field" %>
      <%= f.text_field nil, id: nil, title: "Member Field" %>
    <% end %>

    <%= form.submit %>
  <% end %>
</main>