config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper_openid_connect
  use_doorkeeper
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"
  mount MissionControl::Jobs::Engine, at: "/organization/jobs"
  mount DemoMode::Engine => "/demo"
  mount LetterOpenerWeb::Engine, at: "/organization/letters" if Rails.application.config.action_mailer.delivery_method == :letter_opener

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal healconfig.action_mailer.delivery_method = :letter_openerth status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "my/memberships#new"

  namespace :organization do
    root "members#index", as: :members

    resources :members, param: :username, except: [:index, :edit, :delete] do
      collection do
        resources :exports, only: [:show], param: :type, module: :member
      end
    end

    resources :broadcasts, only: [:index, :destroy, :create]

    resource :config, except: [:edit, :destroy]

    resource :journey, only: [:new, :create] do
      collection do
        resources :strategies, only: [:index], shallow: true, as: "journey_strategies", module: :journey do
          collection do
            scope module: :strategies do
              namespace :password do
                resources :authentications, only: [:new, :create]
              end
              namespace :passkey do
                resources :authentications, only: [:new, :create]
              end
            end
          end
        end
        get "/delete", to: "journeys#delete"
      end
    end

    get "/cemetery", to: "cemeteries#index"
    get "/petitions", to: "petitions#index"

    resources :api_keys, only: [:index, :create, :destroy]

    # TODO: shallow nest inside of Config
    resources :passkeys, only: [:index, :new, :create, :destroy]
  end

  namespace :api do
    resources :members, param: :username, except: [:new, :edit, :delete] do
      member do
        resource :actor, only: :show, module: :member, as: :member_actor, controller: :actors
      end
    end
    resources :broadcasts, except: [:new, :edit, :delete, :update]
  end
  
  namespace :my do
    root to: redirect("/my/membership")

    resource :journey, only: [:new, :create] do
      collection do
        resources :strategies, only: [:index], shallow: true, as: "journey_strategies", module: :journey do
          collection do
            scope module: :strategies do
              namespace :keycode do
                resources :authentications, only: [:new, :create]
              end
              namespace :passkey do
                resources :authentications, only: [:new, :create]
              end
            end
          end
        end
        get "/delete", to: "journeys#delete"
      end
    end

    resource :membership, only: [:new, :create, :show, :update, :destroy] do
      resource :renewals, only: [:create], module: :membership
    end

    namespace :imprint do
      resource :rotations, only: [:create]
    end

    resources :passkeys, only: [:index, :new, :create, :destroy]
  end

  resolve("Membership") { [:membership] }
  resolve("Journey") { [:journey] }
  resolve("Config") { [:config] }
end

app/models/concerns/member/petitioner.rb
module Member::Petitioner
  extend ActiveSupport::Concern

  included do
    has_one :clearance_petition, class_name: "Clearance", dependent: :destroy, inverse_of: :petitioner, as: :petitioner, autosave: true
    default_scope -> { where.missing(:clearance_petition) unless !Config.clearing }
    scope :include_petitioners, -> { unscope(where: :id) }
    scope :petitioners, -> { include_petitioners.where.associated(:clearance_petition) }

    delegate :approve!, to: :clearance_petition
    delegate :reject!, to: :clearance_petition
  end

  def petitioning?
    clearance_petition.present?
  end
end

app/models/member.rb
class Member < ApplicationRecord
  include Expirable
  include Renewable
  include Keycode::Imprintor
  include Mortality
  include Extensibility
  include Verifiable
  include My::Keyable
  include Petitioner

  include SpreadsheetArchitect

  validates :username, format: {with: /\A[a-z0-9]+\z/i}

  def spreadsheet_columns
    [
      :username,
      :name,
      :pronouns,
      :email,
      ["Line 1", address&.line1],
      ["Line 2", address&.line2],
      ["City", address&.city],
      ["Province", address&.province],
      ["Code", address&.code],
      ["Country", address&.country.to_s]
    ] +
      Extension.try(:names).keys.map { |e| [(e.present? ? ActiveSupport::Inflector.humanize(e) : ""), extensions.find_by(name: e)&.content] } +
      [:expires_at, :created_at, :updated_at, :banned]
  end

  # Addressable concern wasn't working
  has_one :address, dependent: :destroy, autosave: true, as: :addressable
  accepts_nested_attributes_for :address, allow_destroy: true, reject_if: :all_blank

  broadcasts_refreshes

  after_destroy_commit do
    broadcast_refresh_to :members
  end

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, format: {with: ::URI::MailTo::EMAIL_REGEXP}, uniqueness: {case_sensitive: false}
  validates :name, presence: true

  before_validation do
    self.email = email&.downcase
    self.username = username&.downcase
  end

  self.primary_key = "username"

  self.condition = "membership"

  self.renew_location = "#{
  begin
    Config.external_url
  rescue
    "united.local"
  end}/my"

  self.expiry_disabled = -> { Config.membership_length < 0 }

  # standard:disable Rails/InverseOf

  has_many :access_grants,
    class_name: "Doorkeeper::AccessGrant",
    foreign_key: :resource_owner_id,
    dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens,
    class_name: "Doorkeeper::AccessToken",
    foreign_key: :resource_owner_id,
    dependent: :delete_all # or :destroy if you need callbacks

  # standard:enable Rails/InverseOf

  def status
    if deceased?
      "deceased"
    elsif petitioning?
      "petitioning"
    elsif banned?
      "banned"
    elsif expired?
      "expired"
    else
      "active"
    end
  end

  def self.where_active
    select do |m|
      !m.expired? && !m.banned?
    end
  end

  def id
    username
  end
end

app/models/organization/keyable.rb
module Organization::Keyable
  extend ActiveSupport::Concern

  included do
    has_one :keyring, as: :keyable, dependent: :destroy, class_name: "Organization::Keyring"
  end

  class_methods do
    delegate :keyring, to: :first, allow_nil: true

    delegate :create_keyring, to: :first
  end
end

app/models/organization/keyring.rb
class Organization::Keyring < Keyring
  self.relying_party = WebAuthn::RelyingParty.new(
    origin: Config.external_url,
    name: "#{Config.organization} Administration"
  )
  attribute :type, :string, default: -> { "Organization::Keyring" }
end

app/controllers/api/member/actor/discoveries_controller.rb
class Api::Member::Actor::DiscoveriesController < Api::BaseController
  skip_before_action :ensure_authenticated
  def new
    if !params[:resource]&.present?
      render plain: "No resource provided", status: 400
      return
    end
    @acct = begin
      URI(params[:resource]).opaque.split("@") 
    rescue 
      render plain: "Invalid Resource URI", status: 400
      return
    end
    if @acct[1] != URI(Config.external_url)&.host && 
    @acct[1] != Config.external_url && 
    @acct[1] != URI(request.base_url).host
        render plain: "Resource doesn't exist here", status: 400
        return
    end
    
    @member = begin
      Member.find(@acct[0])
    rescue
      render plain: "Unable to find user", status: 400
      return
    end
    if @member.blank?
      render plain: "Unable to find user", status: 400
      return
    end
    render formats: :json, content_type: "application/jrd+json"
  end
end

app/controllers/api/member/actors_controller.rb
class Api::Member::ActorsController < Api::BaseController
  def show
    @member = Member.find(params[:username])
    
    render formats: :json, content_type: "application/ld+json"
  end
end

app/controllers/api/members_controller.rb
class Api::MembersController < Api::BaseController
  def index
    @members = Member.all.sort_by(&:created_at).reverse
  end

  def create
    # be sure to use extensions_attributes and not extensions!
    @member = Member.new(member_params)

    if @member.invalid?
      render json: @member.errors, status: 400
    else
      @member.save!
      render "show"
    end
  end

  def update
    @member = Member.find_by(username: params[:username])
    @member.assign_attributes(member_params)

    if @member.invalid?
      render json: @member.errors, status: 400
    else
      @member.save!
      render "show"
    end
  end

  def show
    @member = Member.find_by(username: params[:username])
  end

  def destroy
    Member.find_by(username: params[:username]).destroy!
    render json: Member.ids
  end

  private

  def member_params
    params.require(:member).permit(:username, :name, :email, :pronouns, :banned, :expires_at, :extensions_attributes, address_attributes: [:line1, :line2, :city, :province, :code, :country])
  end
end

app/controllers/organization/api_keys_controller.rb
class Organization::ApiKeysController < Organization::BaseController
  def index
  end

  def create
    p = SecureRandom.base64(54)
    a = Api::Key.create! api_key_params.merge({password: p})
    redirect_back fallback_location: organization_api_keys_path, flash: {"#{a.id}_api_key": p}
  end

  def destroy
    Api::Key.find_by(id: params[:id]).destroy!
    redirect_back fallback_location: organization_api_keys_path
  end

  private

  def api_key_params
    params.require(:api_key).permit(:id, :name)
  end
end

app/controllers/organization/base_controller.rb
class Organization::BaseController < ApplicationController
  before_action :ensure_authenticated
  add_breadcrumb "Organization", :organization_members_path

  def ensure_authenticated
    if !request.env["warden"].authenticated?
      Journey.basecamp = request.env["PATH_INFO"]
      redirect_to new_organization_journey_path
    end
  end

  private

  # For demo mode
  def current_user
    request.env["warden"].user
  end

  def sign_out
    request.env["warden"].logout
  end

  def sign_in(config)
    request.env["warden"].set_user(config)
  end
end

app/controllers/organization/broadcasts_controller.rb
class Organization::BroadcastsController < Organization::BaseController
  def new
  end

  def create
    Broadcast.create! broadcast_params
    redirect_back fallback_location: organization_broadcasts_path
  end

  private

  def broadcast_params
    params.require(:broadcast).permit(:subject, :content)
  end
end

app/controllers/organization/cemeteries_controller.rb
class Organization::CemeteriesController < Organization::BaseController
  add_breadcrumb "Cemetery", :organization_cemetery_path
  def index
    @members = Member.cemetery
  end
end

app/controllers/organization/configs_controller.rb
class Organization::ConfigsController < Organization::BaseController
  skip_before_action :ensure_configured, :ensure_authenticated, only: [:new, :create]

  def new
    if Config.first
      redirect_to organization_members_path, flash: {error: "This instance is already configured"}
    end
  end

  def create
    if Config.first
      redirect_to organization_members_path, flash: {error: "This instance is already configured"}
      return
    end
    c = Config.new(config_params)
    c.save!
    redirect_to organization_members_path
  end

  def show
  end

  def update
    c = Config.first
    c.assign_attributes(config_params)
    if c.invalid?
      errors = "<ul>"
      c.errors.full_messages.each do |e|
        errors += "<li>#{e}</li>"
      end
      errors += "</ul>"
      flash.now[:error] = errors
      render :show, status: :unprocessable_entity
      return
    end
    c.save!
    redirect_back fallback_location: organization_config_path
  end

  private

  def config_params
    params.require(:config).permit(:organization, :external_url, :membership_length, :clearing, :email, :password, extensions: [], smtp: [:server, :port, :username, :password, :box, :domain])
  end
end

app/controllers/organization/journey/base_controller.rb
class Organization::Journey::BaseController < Organization::BaseController
  layout "organization/journeys"

  skip_before_action :ensure_authenticated

  add_breadcrumb "Journey", :new_organization_journey_path
end

app/controllers/organization/journey/strategies/base_controller.rb
class Organization::Journey::Strategies::BaseController < Organization::Journey::BaseController
  add_breadcrumb "Strategies", :organization_journey_strategies_path
end

app/controllers/organization/journey/strategies/passkey/authentications_controller.rb
class Organization::Journey::Strategies::Passkey::AuthenticationsController < Organization::Journey::Strategies::BaseController
  def new
    @options = Journey.explorer.keyring.relying_party.options_for_authentication

    Passkey::Ceremony.reset
    Passkey::Ceremony.challenge = @options.challenge

    add_breadcrumb "Passkey", :new_organization_passkey_authentication_path
  end

  def create
    request.env["warden"].authenticate(:organization_passkey)
    if !request.env["warden"].authenticated?
      flash[:error] = "Unable to log in"
      redirect_back fallback_location: new_organization_passkey_authentication_path, status: :see_other
      return
    end
    redirect_to (Journey.basecamp || organization_members_path), status: :see_other
  end
end

app/controllers/organization/journey/strategies/password/authentications_controller.rb
class Organization::Journey::Strategies::Password::AuthenticationsController < Organization::Journey::Strategies::BaseController
  def new
    add_breadcrumb "Password", new_organization_password_authentication_path
  end

  def create
    request.env["warden"].authenticate(:organization_password)
    if !request.env["warden"].authenticated?
      flash[:error] = "Unable to log in"
      redirect_back fallback_location: new_organization_password_authentication_path
      return
    end
    redirect_to Journey.basecamp || organization_members_path, status: :see_other
  end
end

app/controllers/organization/journey/strategies_controller.rb
class Organization::Journey::StrategiesController < Organization::Journey::Strategies::BaseController
  def index
    @strategies = [{
      name: "Password",
      path: new_organization_password_authentication_path,
      icon: "password.svg"
    }]

    if Journey.explorer&.keyring
      @strategies.push({
        name: "Passkey",
        path: new_organization_passkey_authentication_path,
        icon: "passkey.svg"
      })
    end
  end
end

app/controllers/organization/journeys_controller.rb
class Organization::JourneysController < Organization::Journey::BaseController
  def new
    basecamp = Journey.basecamp
    Journey.reset
    Journey.basecamp = basecamp
  end

  def create
    Journey.explorer = Config.find_by(email: config_params[:email].downcase)
    redirect_to organization_journey_strategies_path, status: :see_other
  end

  def delete
    request.env["warden"].logout
    redirect_to new_organization_journey_path
  end

  private

  def config_params
    params.require(:config).permit(:email)
  end
end

app/controllers/organization/member/exports_controller.rb
class Organization::Member::ExportsController < Organization::BaseController
  def show
    members = Member.order(created_at: :desc)
    @export = members.extend(Exportable).export(params[:type])
    render csv: @export.to_data,
      filename: @export.filename
  end
end

app/controllers/organization/members_controller.rb
class Organization::MembersController < Organization::BaseController
  include ActiveSupport::Inflector

  def index
    @members = Member.order(created_at: :desc)
    respond_to do |format|
      format.html
    end
  end

  def show
    @member = Member.include_deceased.include_petitioners.find_by(username: params[:username])
    add_breadcrumb @member.username, organization_member_path(params[:username])
  end

  def update
    member = Member.include_deceased.include_petitioners.find_by(username: params[:username])
    if member.deceased?
      member.resurrect
    end
    if member.petitioning?
      member.approve!
    end
    member.update!(member_params.merge!({extensions_attributes: mapped_extensions}))
    redirect_to organization_members_path
  end

  def destroy
    member = Member.include_deceased.include_petitioners.find_by(username: params[:username])
    if member.petitioning?
      member.reject!
      member.cremate!
    elsif member.deceased?
      member.cremate!
    else
      member.decease
    end
    redirect_to organization_members_path, status: 303
  end

  private

  def member_params
    params.require(:member).permit(:name, :username, :email, :expires_at, :banned, address_attributes: [:line1, :line2, :city, :province, :code, :country], extensions_attributes: {})
  end

  def mapped_extensions
    attrs = member_params[:extensions_attributes] || {}
    attrs.keys.map { |e| {name: e, content: attrs[e]} }
  end
end

app/views/organization/members/index.html.erb
<%= render "nav" %>

<header>
  <h1 style="margin-bottom: 8px">Members</h1>
  <nav aria-label="Actions" class="subheading-buttons">
    <button id="share" class="subheading-button">Share join link</button>
    <%= link_to organization_cemetery_path do %>
      <button class="subheading-button">Visit cemetery</button>
    <% end %>
    <div style="display: inline-flex; gap: 0;border-radius: 4px;box-sizing: border-box;position: relative;">
      <%= link_to organization_export_path(:csv), data: { turbo: false } do %>
        <button class="subheading-button" style="border-top-right-radius: 0;border-bottom-right-radius: 0;">
          Export
        </button>
      <% end %>
      <details class="dropdown" style="display: inline-flex;">
        <summary class="subheading-button">↓</summary>
        <nav aria-label="Export formats">
          <%= link_to "OpenSlides", organization_export_path(:open_slides), data: { turbo: false } %>
        </div>
      </details>
    </div>
  </nav>
</header>
<%= turbo_stream_from "members" %>
<main id="main">
  <% if Clearance.any? %>
    <% @clearance_count = Clearance.count %>
    <%= link_to organization_petitions_path do %>
    <button style="margin-bottom: 1rem;">Review <%= @clearance_count %> new member<%= @clearance_count > 1 ? "s" : nil %></button>
    <% end %>
  <% end %>
  <table>
    <thead>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Expires on</th>
      <th>Member since</th>
      <th>Status</th>
      <th></th>
    </thead>
    <tbody>
      <% @members.each do |m| %>
        <%= turbo_stream_from m %>
        <tr>
          <td><%= m.name %></td>
          <td><%= m.username %></td>  
          <td><%= m.email %></td>
          <td><%= local_relative_time(m.expires_at, type: "time-or-date") %></td>
          <td><%= local_relative_time(m.created_at, type: "time-or-date") %></td>
          <td><span class="<%= m.status %>-chip"><%= m.status %></span></td>
          <td>
            <%= link_to organization_member_path(m) do %>
              <button>Edit</button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

<style>
  details {
    summary {
      height: 53%;
      display: inline-flex;
      border-radius: 4px;
      border-top-left-radius: 0;
      border-bottom-left-radius: 0;
      padding: 5px 10px;
      background-color: var(--red-11) !important;
      border: 2px solid var(--red-11) !important;
      cursor: pointer;
      transition: ease-in-out 0.2s;
      &:hover {
        background-color: var(--red-12) !important;
        border-color: var(--red-12) !important;
      }
    }

    nav {
      position: absolute;
      top: 30px;
      background: var(--red-11);
      color: white;
      border-radius: 4px;
      display: flex;
      flex-direction: column;
      border-top-left-radius: 0;
      left: 65px;
      width: max-content;
      gap: 0.5rem;
      overflow: hidden;
      a {
        font-weight: 600;
        font-size: smaller;
        padding: 0.5rem 10px;
        transition: ease-in-out 0.2s;
        color: var(--sand-1);
        &:hover {
          background-color: var(--red-12);
        }
      }
    }
  }

  details[open] {
    summary {
      border-bottom-right-radius: 0;
    }
  }
</style>

<script type="module">
  const shareBtn = document.querySelector("button#share")

  if (!navigator.share) {
    shareBtn.textContent = "Copy join link"
  }

  shareBtn.addEventListener("click", async (event) => {
    if (navigator.share) {
      // Use Web Share API
      await navigator.share({
        title: "Join <%= Config.organization %>",
        text: "Become a member of <%= Config.organization %>!",
        url: "<%= new_my_membership_url %>",
      })
    } else {
      // Copy to clipboard if Web Share is unavailable
      await navigator.clipboard.writeText("<%= new_my_membership_url %>");
      alert("Copied join link to clipboard!")
    }
  })
</script>

app/views/organization/members/show.html.erb
<%= render "breadcrumbs" %>
<h1><%= @member.name %></h1>
<%= turbo_stream_from @member %>
<%= form_with model: @member, url: organization_member_path, scope: :member do |form| %>
  <div>
    <%= form.label :name, "Full name" %>
    <%= form.text_field :name, placeholder: "Fionah United" %>
  </div>
  <div>
    <%= form.label :name, "Username" %>
    <%= form.text_field :username, placeholder: "fionahu" %>
  </div>
  <div>
    <%= form.label :email, "Email" %>
    <%= form.email_field :email, placeholder: "fionahu@obl.ong" %>
  </div>
  <h3 style="margin: 0; margin-top: 0.5rem;">Postal Address</h3>
  <%= form.fields_for :address, @member.address || Address.new(addressable_id: @member, addressable_type: Member) do |address_form| %>
    <div>
      <%= address_form.label :line1, "Number and Street" %>
      <%= address_form.text_field :line1 %>
    </div>
    <div>
      <%= address_form.label :line2, "Line 2" %>
      <%= address_form.text_field :line2 %>
    </div>
    <div style="display: flex; flex-direction: row; justify-content: space-between;">
      <div style="max-width: 50%;">
        <%= address_form.label :city %>
        <%= address_form.text_field :city %>
      </div>
      <div style="max-width: 50%;">
        <%= address_form.label :province %>
        <%= address_form.text_field :province %>
      </div>
    </div>
    <div style="display: flex; flex-direction: row; justify-content: space-between;">
      <div style="width: 50%">
        <%= address_form.label :code, "Postal Code" %>
        <%= address_form.text_field :code %>
      </div>
      <div style="width: 50%">
        <%= address_form.label :country %>
        <%= address_form.select :country, Domesticable::Country.all.prepend(nil) %>
      </div>
    </div>
  <% end %>
  <%= form.fields_for :extensions_attributes do |extensions_form| %>
    <% Config.extensions.each do |e| %>
      <div>
        <%= extensions_form.label e, ActiveSupport::Inflector.humanize(e.to_s) %>
        <%= extensions_form.text_field e, value: @member.extensions.find_by(name: e)&.content %>
      </div>
    <% end %>
  <% end %>

  <div style="height: 100%; width: 100%;">
    <%= form.label :signature, "Signature" %>
    <%= form.hidden_field :signature %>
    <div style="position: relative; width: 100%;">
      <canvas class="signature" style="cursor: not-allowed; pointer-events: none;">
      </canvas>
    </div>
  </div>
  <div>
    <%= form.label :expires_at, "Expires on" %>
    <%= form.date_field :expires_at, placeholder: DateTime.now + 1.year %>
  </div>
  <div>
    <%= form.label :banned, "Banned?" %>
    <%= form.check_box :banned %>
  </div>
  <% if @member.deceased? %>
    <%= form.submit "Resurrect and Update" %>
    <%= form.submit "Cremate", class: "delete", formmethod: :delete, data: { turbo_confirm: "Are you sure you want to permanently cremate #{@member.name}?" } %>
  <% elsif @member.petitioning? %>
    <%= form.submit "Approve" %>
    <%= form.submit "Reject", class: "delete", formmethod: :delete, data: { turbo_confirm: "Are you sure you want to reject #{@member.name}?" } %>
  <% else %>
    <%= form.submit "Update" %>
    <%= form.submit "Decease", class: "delete", formmethod: :delete, data: { turbo_confirm: "Are you sure you want to decease #{@member.name}?" } %>
  <% end %>
<% end %>

<script>
  import("signature_pad").then((mod) => {
    const canvas = document.querySelector("canvas")
    const SignaturePad = mod.default;
    const bgColor = window.matchMedia('(prefers-color-scheme: dark)').matches ? "#111110": "#fdfdfc";

    const pad = new SignaturePad(canvas, {
      penColor: window.matchMedia('(prefers-color-scheme: dark)').matches ? "#FBFBFE" : "black"
    });

    pad.off();

    function resizeCanvas() {
      const ratio = Math.max(window.devicePixelRatio || 1, 1);
      canvas.width = canvas.offsetWidth * ratio;
      canvas.height = 150 * ratio;
      canvas.getContext("2d").scale(ratio, ratio);
      pad.clear(); // otherwise isEmpty() might return incorrect value
    }

    window.addEventListener("resize", resizeCanvas);
    resizeCanvas();

    const data = JSON.parse(document.querySelector("#member_signature").value)
    data.forEach((p) => {
      p.penColor = window.matchMedia('(prefers-color-scheme: dark)').matches ? "#FBFBFE" : "black"
    })
    pad.fromData(data)

    window.matchMedia('(prefers-color-scheme: dark)').addListener((e) => {
      let currentData = pad.toData();
      pad.clear()
      currentData.forEach((p) => {
        p.penColor = window.matchMedia('(prefers-color-scheme: dark)').matches ? "#FBFBFE" : "black"
      })
      pad.fromData(currentData)
    })
  })
</script>